engines:
  golint:
    enabled: true
  eslint:
    enabled: true
    config:
    extensions:
    - .es6
    - .js
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**.es6"
  - "**.css"
  - "**.js"
exclude_paths:
- src/**/*.spec.js
- dist/**