export const REQUEST_USER_PROJECTS="REQUEST_USER_PROJECTS";
export const REQUEST_USER_PROJECT="REQUEST_USER_PROJECT";
export const REQUEST_DEPLOY_PROJECT="REQUEST_DEPLOY_PROJECT";
export const SET_PROJECT_SERVERS="SET_PROJECT_SERVERS";
export const SET_PROJECT_DEPLOYS="SET_PROJECT_DEPLOYS";
export const SET_USER_PROJECTS="SET_USER_PROJECTS";
export const SET_USER_PROJECT="SET_USER_PROJECT";
export const SET_USER_PROJECT_DEV_ENVIRONMENT="SET_USER_PROJECT_DEV_ENVIRONMENT";
